In [12]:
from sklearn.model_selection import KFold
import numpy as np
X = np.array([[1, 2], [3, 4], [9, 8], [7, 0]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=3)
kf.get_n_splits(X)

print(kf)
# print(kf.split)

for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    print(X_train) 
    print('kk')
    print(X_test)
    y_train, y_test = y[train_index], y[test_index]
    print(y_train) 
    print('yy')
    print(y_test)



KFold(n_splits=3, random_state=None, shuffle=False)
TRAIN: [2 3] TEST: [0 1]
[[9 8]
 [7 0]]
kk
[[1 2]
 [3 4]]
[3 4]
yy
[1 2]
TRAIN: [0 1 3] TEST: [2]
[[1 2]
 [3 4]
 [7 0]]
kk
[[9 8]]
[1 2 4]
yy
[3]
TRAIN: [0 1 2] TEST: [3]
[[1 2]
 [3 4]
 [9 8]]
kk
[[7 0]]
[1 2 3]
yy
[4]
